### ISSUE TITLE
reparametrization trick bug

### ISSUE THREAD

**Issue by TheMrGhostman** [federicobergamin/Variational_Autoencoders_in_Julia#1]
hi, do you know that you are sampling from uniform distribution instead of gaussian distribution?
That is probably reason why your approximate KL divergence does not converge.

**Comment by federicobergamin** [comment]
Hi @TheMrGhostman sorry for this late reply and thanks to have spent some time looking at this "not so complete" directory. You are right, I should have used randn and not rand, because $\epsilon \sim N(0,1)$. I do not know if this will help in avoiding getting NaN if I use the approximate KL instead of the analytical one. I will try.
